export const dom = {
    modelSelector: document.getElementById('model-selector'),
    tokenCountDisplay: document.getElementById('token-count-display'),
    settingsBtn: document.getElementById('settings-btn'),
    historyBtn: document.getElementById('history-btn'),
    chatContainer: document.getElementById('chat-container'),
    resizeHandle: document.getElementById('resize-handle'),
    messageInput: document.getElementById('message-input'),
    sendBtn: document.getElementById('send-btn'),
    settingsModal: document.getElementById('settings-modal'),
    llmConfigsContainer: document.getElementById('llm-configs-container'),
    addModelBtn: document.getElementById('add-model-btn'),
    closeSettingsBtn: document.getElementById('close-settings-btn'),
    historyModal: document.getElementById('history-modal'),
    conversationsContainer: document.getElementById('conversations-container'),
    addConversationBtn: document.getElementById('add-conversation-btn'),
    renameConversationBtn: document.getElementById('rename-conversation-btn'),
    deleteConversationBtn: document.getElementById('delete-conversation-btn'),
    compressConversationBtn: document.getElementById('compress-conversation-btn'),
    importConversationBtn: document.getElementById('import-conversation-btn'),
    exportConversationBtn: document.getElementById('export-conversation-btn'),
    loadConversationBtn: document.getElementById('load-conversation-btn'),
    closeHistoryBtn: document.getElementById('close-history-btn'),
    clearChatBtn: document.getElementById('clear-chat-btn'),
    importSettingsBtn: document.getElementById('import-settings-btn'),
    exportSettingsBtn: document.getElementById('export-settings-btn'),
    copyChatBtn: document.getElementById('copy-chat-btn'),
    footer: document.querySelector('footer'),
    attachFileBtn: document.getElementById('attach-file-btn'),
    attachedFilesContainer: document.getElementById('attached-files-container'),
    cancelEditBtn: document.getElementById('cancel-edit-btn'),
    proxyUrl: document.getElementById('proxy-url'),
    sequentialWorkflowRequests: document.getElementById('sequential-workflow-requests'),
    workflowRequestDelay: document.getElementById('workflow-request-delay'),
    apiRetryDelay: document.getElementById('api-retry-delay'),

    settingsTabs: document.getElementById('settings-tabs'),
    tabGlobal: document.getElementById('tab-global'),
    tabModels: document.getElementById('tab-models'),
    tabWorkflows: document.getElementById('tab-workflows'),
    
    workflowsList: document.getElementById('workflows-list'),
    addWorkflowBtn: document.getElementById('add-workflow-btn'),
    
    workflowEditorOverlay: document.getElementById('workflow-editor-overlay'),
    workflowNameInput: document.getElementById('workflow-name-input'),
    workflowScriptInput: document.getElementById('workflow-script-input'),
    workflowEditorCancelBtn: document.getElementById('workflow-editor-cancel-btn'),
};
